import { ApolloClient, gql, InMemoryCache } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import { GetLaunchesQuery, Launch } from "../graphql/generated";
import { isNotNull, isNotUndefined } from "../lib/type-helpers";
import styles from "../styles/Home.module.css";

type HomeProps = {
  launches: Launch[];
};

type StaticHomeProps = {
  props: HomeProps;
};

export async function getStaticProps(): Promise<StaticHomeProps> {
  const client = new ApolloClient({
    uri: "https://api.spacex.land/graphql/",
    cache: new InMemoryCache(),
  });
  const { data } = await client.query<GetLaunchesQuery>({
    query: gql`
      query GetLaunches {
        launches(limit: 10) {
          id
          mission_name
          launch_date_local
          launch_site {
            site_name_long
          }
          links {
            article_link
            video_link
            mission_patch
          }
          rocket {
            rocket_name
          }
        }
      }
    `,
  });
  const launches: Launch[] =
    data.launches?.filter(isNotUndefined).filter(isNotNull) ?? [];
  return { props: { launches } };
}

const Home: NextPage<HomeProps> = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SpaceX launches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>SpaceX launches GraphQL test</h1>

        <div className={styles.grid}>
          {props.launches?.map((launch) => {
            return (
              <a
                key={launch.id}
                href={launch.links?.video_link ?? ""}
                className={styles.card}
              >
                <h3>{launch.mission_name}</h3>
                <p>
                  <strong>Launch Date:</strong>{" "}
                  {new Date(launch.launch_date_local).toLocaleDateString(
                    "en-US"
                  )}
                </p>
              </a>
            );
          })}
        </div>
      </main>
    </div>
  );
};

export default Home;
